#!/bin/bash
STATUS_SRC=/data/Homepage/.status
STATUS=/data/Homepage/status
echo -e "\e[1mMAIN\e[0m: http://repo.anthonos.org"
MAIN=$(curl http://repo.anthonos.org/last_update)
echo -e "\e[1m======== MIRRORS ========\e[0m"

# PHP i18n used:
  # date_error: 'Error when converting date, contact'
  # mirror_admin: 'Mirror admin'
  # sites/* <= $SITENAME
  # main_name: 'AOSC Main Server' // (repo.anthonos.org)
  # page_gen: 'Page Generated at:' // $(date -u)

# PHP notice and workaround:
  # The langues 2D array isn't working inside the double quote 
  #  (It returns Array['something'] instead). There may be something to do with the 
  #  Word-splitting.

# SITE: HTTP(S)/FTP address to mirror
# SITENAME_{EN,SC,TC}: Mirror Name
# CONTACT: email, irc, etc.
# To ignore site, make it hidden.
generate_site(){
  unset SITE SITENAME{,_EN,_SC,_TC}
  . ${STATUS_SRC}/sites/$1
  SITENAME_EN=${SITENAME_EN:-$SITENAME}
  SITENAME_SC=${SITENAME_SC:-$SITENAME_EN}
  SITENAME_TC=${SITENAME_TC:-$SITENAME_SC}
  echo -e "\e[1m${SITENAME_EN}\e[0m: ${SITE} ($1)"
  TIMESTAMP=`curl -m 10 ${SITE}/last_update` 

  # Is it a date-generated string?
  if ! (date_block=$(date -ud@$TIMESTAMP) 2>&1 | grep ".*"); then ISDATE=true; else date_block="<?=\$langues[\$langue]['date_error'] $(print_contact) ?>"; fi
  [ $ISDATE ] && delta=$(($MAIN-$TIMESTAMP))
  if [ "$delta" == "0" ]; then
    LABEL="success"
    LATEST="Yes"
  else LATEST="No"
    if [ "$delta" -lt "4000" ]
    then LABEL="warning"
    else LABEL="danger"
    fi
  fi
  latest_block="<span class='label label-$LABEL' title='ΔT=${delta:-N/A} secs'>$LATEST</span>"
  echo "<tr class="$LABEL"><td><?=\$langues[\$langue]['$1'] ?></td><td><a href=\"${SITE}\">${SITE}</a></td><td>${date_block}</td><td>${latest_block}</td></tr>" >> ${STATUS}/index.php
  # Dump SITENAMEs, with fallbacks
  echo "    '$1' => '$SITENAME_EN'," >> MIRROR_NAME_EN
  echo "    '$1' => '$SITENAME_SC'," >> MIRROR_NAME_SC
  echo "    '$1' => '$SITENAME_TC'," >> MIRROR_NAME_TC
}

# PHP Helper
print_contact() {
  if [ $CONTACT ]; then echo "\"$CONTACT\""; else echo "\$langues[\$langue]['mirror_admin']"; fi
}

FOOTER="</tbody></table><p><?php echo\$langues[\$langue]['page_gen'] ?>$(date -u)</p></div><script type=text/javascript src='https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js'></script><script type=text/javascript src='https://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js'></script></body></html>"
cat ${STATUS_SRC}/header.php > "${STATUS}/index.php"
rm -f MIRROR_NAME_{EN,SC,TC}
echo "<tr class="well"><td><?php echo \$langues[\$langue]['main_name'] ?></td><td><a href=\"http://repo.anthonos.org/\">http://repo.anthonos.org/</a></td><td>$(date -ud@$MAIN)</td><td><span class='label label-info'<?php echo \$langues[\$langue]['NA'] ?></span></td></tr>" >> ${STATUS}/index.php
for i in $(ls ${STATUS_SRC}/sites); do generate_site $i; done
echo "$FOOTER" >> "${STATUS}/index.php"

sed -e '/\[MIRROR_NAME_EN\]/{
r MIRROR_NAME_EN
d }' -i "${STATUS}/index.php"
sed -e '/\[MIRROR_NAME_SC\]/{
r MIRROR_NAME_SC
d }' -i "${STATUS}/index.php"
sed -e '/\[MIRROR_NAME_TC\]/{
r MIRROR_NAME_TC
d }' -i "${STATUS}/index.php"

# Clean your butt
rm -f MIRROR_NAME_{EN,SC,TC}
